### ISSUE TITLE
[E2E test] More timeout setting in Travis

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/browser-redux#13]
The E2E tests is often an error in Travis CI.
I think we may need more timeout in CI. (use `is-ci` npm package)

@zalmoxisus you think?

**Comment by zalmoxisus** [comment]
Yeh:). Just was [looking](https://github.com/zalmoxisus/browser-redux/commit/9f03165e794bbe9fa4f6f8f9489413623fd6a098) into this problem.
Great package, by the way (didn't know about it), just wondering, if travis sometimes needs more timeout, maybe some users also need it having not so fast machine. Why not just to increase it for all tests? I was thinking about [10000 ms](https://github.com/zalmoxisus/browser-redux/blob/testing/test/shared/functions.js#L11).

**Comment by zalmoxisus** [comment]
Added a [global timeout](https://github.com/zalmoxisus/browser-redux/blob/3548c357db156f83fccc3495689c9e446d2e0499/test/chrome/extension.js#L10) in [3548c357db156f83fccc3495689c9e446d2e0499](https://github.com/zalmoxisus/browser-redux/commit/3548c357db156f83fccc3495689c9e446d2e0499). Even though, E2E tests sometime fail to open Chrome or to load the extension (not sure), which doesn't seem to be solved with a bigger timeout. Reloading the build on travis helps, so it could be related to some bugs on their side. What do you think, @jhen0409?

**Comment by zalmoxisus** [comment]
The container-based infrastructure seems to be more stable. There are problems only for chrome apps test. Sometimes the app window cannot be opened. Fixed in https://github.com/zalmoxisus/browser-redux/commit/9d3162e39fe9e0b21fd85e1267e93f4ab00d09cc by making a second attempt to open the window.
