### ISSUE TITLE
Support Immutable data structures in reducers

### ISSUE THREAD

**Issue by gurkerl83** [zalmoxisus/browser-redux#16]
Hi,
tried several approaches integrating immutable.js in counter reducer starting from using redux-persist-immutable and other immutable enabling redux libraries. Unfortunately the experiment is not working so I try to reach out for some hints. I think one issue might be the combineReducers (browser-redux-bg) calls in configureStore to recognise immutable.js.

Thanks!

**Comment by zalmoxisus** [comment]
Hey @gurkerl83,

I never used immutable.js, but I do want to support different user cases with this boilerplate.

I think you are right. If you use [redux-immutablejs](https://github.com/indexiatech/redux-immutablejs), you have to use: `import { combineReducers } from 'redux-immutablejs';`. I moved `combineReducers` from `browser-redux-bg` in the last commit. But I'm not sure redux-immutablejs' combineReducers will be able to combine bg reducers, which aren't immutable. If not, you have to skip `bgReducer` and use `combineReducers({ ...reducers })`. I will implement a better way for using background's store in 0.5. 

Be sure to run 'npm i' and implement the last changes from the boilerplate (we also changed completely the way of using redux-persist).

Probably, you will still need [redux-persist-immutable](https://github.com/rt2zz/redux-persist-immutable) to rehydrate nested immutable data.


BTW, what are the advantages of using immutable.js here? AFAIK, it is useful for:
- preventing mutating states by mistake, which is already solved by `redux-immutable-state-invariant`.
- faster performance and better memory consumption with large arrays and objects, but storing and syncing large data will reduce the performance a lot. So, you have to add such reducers to blacklist for `browser-redux-sync`.

**Comment by rt2zz** [comment]
Also it is worth noting that `redux-persist-immutable` only works with immutable sub state, consequently does not work with `redux-immtablejs` because that creates a top level immutable Map.

Similar to @zalmoxisus I am open to supporting it, but as I do not use immutable.js, I am unopinionated on how best to do that.

**Comment by zalmoxisus** [comment]
Now we do not rehydrate states anymore and it is easy to use immutable data structures. We still use `redux-persist` to get the initial values from the `chrome.storage.local`, but you may skip it (if you don't want to persist the states on browser restart), though it's easy to reimplement it by yourself or probably using `redux-persist-immutable`.

If it still goes wrong or you want to share the experience, feel free to reopen the ticket or to open another one.
