### ISSUE TITLE
calling background functions triggers twice

### ISSUE THREAD

**Issue by gurkerl83** [zalmoxisus/browser-redux#18]
Hi, 
I don`t know if this is the intended result, but subscribing to the store through

```javascript
store.subscribe(handleChange)
```
(within src/browser/extension/background/badge.js) 

triggers **twice** if the increment function was called with 

```javascript
bg('increment')
```
(from src/app/components/Counter.js) .

   badge.js compares previousValue and currentValue and decides if to update the badge text.

I don`t know anything about redux-persist and other involvement libraries but causing an automated secondary call of the listener function requires a state traversal like **previousValue and currentValue** even if the intended function call (background script) does not depend / involve on any state changes e.g. the increment action changing the **state.counter.count** value.

Maybe someone could explain which parts are responsible calling the listeners?

Thanks!

**Comment by zalmoxisus** [comment]
Hey, @gurkerl83.

Yes, it is the intended result as the state is changed twice:

1. The background page receive the command from an other page through a state rehydrate action.
2. The background page dispatch a new action ('increment').

The idea of this approach was to replace the classic [chrome extension messaging](https://developer.chrome.com/extensions/messaging) with just state rehydratations (chrome/local storage listiner), so it would be easy to make a cross browser extension and you have to care only about actions and states. But as you see, we loose the performance. As I told, I want to implement a better way for using background's store in v0.5.

I will create a new issue with the proposal for v0.5. Any suggestions are welcome.

**Comment by zalmoxisus** [comment]
I created [a simple redux middleware](https://github.com/zalmoxisus/redux-notify/blob/master/src/index.js), which notifies when counter is changed, and now use a redux action to update the badge. Any feedback regarding this solution is welcome.
