### ISSUE TITLE
Mixing import and require

### ISSUE THREAD

**Issue by emschwartz** [zalmoxisus/browser-redux#26]
If I'm interpreting this correctly, I think these lines https://github.com/zalmoxisus/browser-redux/blob/master/src/app/store/configureStore.js#L9-L10 will only work with the `add-module-exports` plugin that is included in [`webpack/dev.config.js`](https://github.com/zalmoxisus/browser-redux/blob/master/webpack/dev.config.js#L35) but not in [`webpack/prod.config.js`](https://github.com/zalmoxisus/browser-redux/blob/master/webpack/prod.config.js).

**Comment by zalmoxisus** [comment]
Hey @emschwartz,

As tests pass, there are no problems in production. It works because we import those modules from inside (they aren't build in commonjs). In case we make them as a separate npm packages, we'll have to use `add-module-exports` or to add `.default` when requiring.

**Comment by emschwartz** [comment]
I'm working on a modified version of the boilerplate so it may have been something wrong with my version. I ran into errors saying the module imported there wasn't a function because it wasn't handling the `.default` properly but never mind if it's not an issue for others
