### ISSUE TITLE
Question about storage sync / debounce

### ISSUE THREAD

**Issue by rt2zz** [zalmoxisus/browser-redux#4]
Right now redux-persist has a 33ms debounce built in to the storage set calls. This does not make sense for apps that use storage as a type of messaging bus. My thought is we should add a debounce option to redux-persists that can either be false or an integer number of ms.

Since your project is on the top of my mind right now, @zalmoxisus does this sound right to you?

**Comment by zalmoxisus** [comment]
@rt2zz, yes, having this configurable would be great, as I still intend to use localStorage for Safari extensions. What is the purpose of the debounce?

BTW, I noticed that when using redux-devtools, redux-persist stores the initial state, then rehydrates and store states again with the rehydrated value (you can notice that even in the demo gif when the app is opened from the context menu). If I remove redux-devtools, the initial state isn't stored as the initialization goes faster.

**Comment by rt2zz** [comment]
good info, I will ping you when I have implemented something on the redux-persist side
